"--Load up Pathogen
call pathogen#runtime_append_all_bundles()
call pathogen#helptags()
filetype off
syntax on
filetype plugin on

" choose color scheme
colorscheme wombat
set background=dark

"---basic settings
set tabstop=2
set shiftwidth=2
set nowrap
set textwidth=120
set incsearch
set smartindent
set showcmd
set splitbelow
set nohlsearch
set expandtab
set wildmode=longest,full
set wildmenu
set visualbell t_vb=
set nocp

" toggle comments
nmap ,c gcc
vmap ,c gc

" toggle line numbers
map <C-z> :set invnumber<Enter>

" goto beginning and end of line
map <C-i> I<Esc>
map <C-a> A<Esc>

" jump between sub-views
map <C-h> <C-w>h
map <C-j> <C-w>j
map <C-k> <C-w>k
map <C-l> <C-w>l

" format text to fit into paragraphs
map <C-f> {gq}

" NERDTree setup
map <C-t> :NERDTreeToggle<CR>
map <C-n> :NERDTreeFocus<CR>
map <C-b> :NERDTree<CR>:BookmarkToRoot 

" Minibuffer setup
map <C-m> :MiniBufExplorer<CR>

let xml_use_xhtml=1
let NERDChristmasTree=1

" setup specials for file name extensions
augroup syntax
    autocmd!
  au BufNewFile,BufRead *.rhtml     set syn=eruby
  au BufNewFile,BufRead *.rsel      set syn=ruby
  au BufNewFile,BufRead *.erb       set syn=eruby
  au BufNewFile,BufRead *.tex       set syn=tex
  au BufNewFile,BufRead *.scss      set syn=scss.css
  au BufNewFile,BufRead *.sass      set syn=sass.css
  au BufRead,BufNewFile *.scss      set syn=scss.css
  au BufRead,BufNewFile *.sass      set syn=sass.css
  au BufRead,BufNewFile *.template  set syn=cpp
  au BufRead,BufNewFile *.m         set syn=objc
  au BufRead,BufNewFile *.mm        set syn=objc
  au BufRead,BufNewFile *.rdf       set syn=xml
  au BufRead,BufNewFile *.xul       set syn=xml
  au BufRead,BufNewFile *.haml      set syn=haml
augroup end

augroup formating
    autocmd!
    autocmd BufRead,BufNewFile Makefile*  set noexpandtab
    autocmd BufRead,BufNewFile *.py       set noexpandtab
    autocmd BufRead,BufNewFile *.txt      set nosmartindent

    autocmd BufRead,BufNewFile *.haml     set textwidth=0
    autocmd BufRead,BufNewFile *.py       set textwidth=0
    autocmd BufRead,BufNewFile *.rb       set textwidth=0
    autocmd BufRead,BufNewFile *.m        set textwidth=0
    autocmd BufRead,BufNewFile *.c        set textwidth=0
augroup end

if has ("autocmd")
  filetype plugin indent on
endif

" Read svc.gz files
au BufReadCmd   *.svc.gz      call tar#Browse(expand("<amatch>"))
au BufReadCmd   *.xiv.gz      call tar#Browse(expand("<amatch>"))
au BufReadCmd   *.ds.gz       call tar#Browse(expand("<amatch>"))

" Fuzzy Finder maps
let mapleader = ","
map <leader>F :FufFile<CR>
map <leader>f :FufTaggedFile<CR>
map <leader>t :FufTag<CR>

" Alignment shortcuts
let mapleader = ","
nmap <leader>a= :Tabularize /=<CR>
vmap <leader>a= :Tabularize /=<CR>
nmap <leader>a> :Tabularize /[=>]><CR>
vmap <leader>a> :Tabularize /[=>]><CR>
nmap <leader>a, :Tabularize /,\zs<CR>
vmap <leader>a, :Tabularize /,\zs<CR>
nmap <leader>a: :Tabularize /:\zs<CR>
vmap <leader>a: :Tabularize /:\zs<CR>
nmap <leader>at :Tabularize /
vmap <leader>at :Tabularize /

" Alignment shortcuts
let mapleader = ","
nmap <leader>. mb
nmap <leader>, mv

" Surround shortcuts
let mapleader = ","
nmap <leader>s ys
nmap <leader>S yss
vmap <leader>s S


