# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="shevertalov"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew cap gem git osx perl rails ssh-agent svn taskwarrior ruby bundler)

source $ZSH/oh-my-zsh.sh
source $ZSH/custom/zsh-syntax-highlighting-filetypes.zsh

eval $( /usr/local/bin/gdircolors -b $HOME/.LS_COLORS )


# Customize to your needs...
#
setopt autocd extendedglob nomatch notify
setopt nobeep                  # i hate beeps
unsetopt beep
unsetopt correct_all
unsetopt share_history
setopt autocd                  # change to dirs without cd
setopt pushdignoredups         # and don't duplicate them
setopt completeinword          # not just at the end
setopt alwaystoend             # when complete from middle, move cursor
setopt hash_listall
setopt nopromptcr              # don't add \n which overwrites cmds with no \n
setopt histverify              # when using ! cmds, confirm first
setopt interactivecomments     # escape commands so i can use them later
setopt printexitvalue          # alert me if something's failed
setopt hist_ignore_dups        # ignore same commands run twice+
setopt appendhistory           # don't overwrite history
bindkey -e

#### ALIAS ####
#general commands
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias h='history'
alias j='jobs -l'
alias which='type -a'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias path='echo -e ${PATH//:/\\n}'
alias du='du -h'
alias df='df -h'
alias ls='gls -G -F -X --color=yes'
alias lss='ls -lrS'
alias lc='ls'
alias lsd='ls -d'
alias lsda='ls -AlhFd'
alias la='ls -AlhF |less'
alias lr='ls -lhR'
alias lt='ls -lhsrt'
alias lm='ls -lh|less'
alias ll='ls -lh|less'
alias l='ls -l -h'
alias la='ls -alh'
alias dirs='ls -lF | grep /'
alias q='exit'
alias psg='ps -ef | grep '
alias new='screen -t '
alias hsg='history | grep '
alias pwd='pwd -P'

export EDITOR='/usr/bin/vim'

zmodload zsh/complist

[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.

export PATH=/usr/local/mysql/bin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:$HOME/.rvm/bin



#function to setup the ruby environment and go to a specific folder
function go() {
    cd $1
    rvm use $2
    export GEM_HOME=$1/gems/1.8.7
    export GEM_PATH=$1/gems/1.8.7/bin
    export PATH=$1/gems/1.8.7/bin:$PATH
}

#find and execute
function fiec() { find $1 -type f -iname '*'${2:-}'*' -exec ${3:-file} {} \;; }

# include custom path's and aliases if they exist
if [ -f ~/.zshrc_custom ]; then
  source ~/.zshrc_custom
fi

