# Path to your oh-my-zsh configuration.
export ZSH=$HOME/.oh-my-zsh

# Set to the name theme to load.
# Look in ~/.oh-my-zsh/themes/
export ZSH_THEME="shevertalov"

# Set to this to use case-sensitive completion
# export CASE_SENSITIVE="true"

# Comment this out to disable weekly auto-update checks
# export DISABLE_AUTO_UPDATE="true"

# Uncomment following line if you want to disable colors in ls
# export DISABLE_LS_COLORS="true"

# Uncomment following line if you want to disable autosetting terminal title.
# export DISABLE_AUTO_TITLE="true"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(brew cap gem git osx perl rails3 ssh-agent svn taskwarrior ruby bundler)

source $ZSH/oh-my-zsh.sh

eval $( gdircolors -b $HOME/.LS_COLORS )

source $ZSH/custom/zsh-syntax-highlighting-filetypes.zsh

# Customize to your needs...
#
setopt appendhistory autocd extendedglob nomatch notify
setopt nobeep                  # i hate beeps
setopt autocd                  # change to dirs without cd
setopt pushdignoredups         # and don't duplicate them
setopt completeinword          # not just at the end
setopt alwaystoend             # when complete from middle, move cursor
#setopt correct                 # spelling correction
setopt hash_listall
setopt nopromptcr              # don't add \n which overwrites cmds with no \n
setopt histverify              # when using ! cmds, confirm first
setopt interactivecomments     # escape commands so i can use them later
setopt printexitvalue          # alert me if something's failed
setopt hist_ignore_dups        # ignore same commands run twice+
setopt appendhistory           # don't overwrite history
unsetopt beep
bindkey -e

#### ALIAS ####
#general commands
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias h='history'
alias j='jobs -l'
alias r='rlogin'
alias which='type -a'
alias ..='cd ..'
alias ...='cd ../..'
alias cd.='cd ..'
alias cd..='cd ../..'
alias cd...='cd ../../..'
alias path='echo -e ${PATH//:/\\n}'
alias du='du -h'
alias df='df -h'
alias ls='gls -G -F -X --color=yes'
alias lss='ls -lrS'
alias lc='ls'
alias lsd='ls -d'
alias lsda='ls -AlhFd'
alias la='ls -AlhF |less'
alias lr='ls -lhR'
alias lt='ls -lhsrt'
alias lm='ls -lh|less'
alias ll='ls -lh|less'
alias l='ls -l -h'
alias la='ls -alh'
alias dirsh='ls -alF | grep /'
alias dirs='ls -lF | grep /'
alias q='exit'
alias psg='ps -ef | grep '
alias new='screen -t '
alias hsg='history | grep '
alias pwd='pwd -P'
##mac specific navi_mac stuff
alias curc='cd ~/projects/classes/current'
alias matlab='/Applications/MATLAB_R2008a/bin/matlab -nodisplay -nojvm'

alias tls='run_cat.sh "task list project.has:"'
alias hpu='hg pull -u'

alias shoes='/Users/ms333/projects/tools/shoes/Shoes.app/Contents/MacOS/shoes'

#
export EDITOR='/usr/bin/vim'

#PS1='%n@%m:%~ [%h | %j]%# '
#export PS1="${PURPLE}[%n @ %m : %T-%D]"$'\n'"${GREEN}%~ ${WHITE}"$'\n'"$"
#
#export LS_COLORS=$ZLS_COLORS
#
#export LSCOLORS=ExFxCxDxBxegedabagacad
#

zmodload zsh/complist

export PATH=/usr/local/bin/:/usr/local/mysql/bin:$PATH
export PATH=$PATH:/Applications/MATLAB7/bin/
export PATH=$PATH:~/projects/useful_scripts/
export PATH=$PATH:/usr/bin/jruby/bin/
export PATH=$PATH:/usr/local/bin
export PATH=/System/Library/Frameworks/JavaVM.framework/Versions/1.6/Commands/:$PATH
export PATH=/opt/mongodb-osx-x86_64-1.8.1/bin:$PATH

export MAGICK_HOME=/usr/local/ImageMagick-6.7.1
export PATH=$MAGICK_HOME/bin:$PATH
#export DYLD_LIBRARY_PATH=$MAGICK_HOME/lib
export PATH=/Applications/Shoes.app/Contents/MacOS/:$PATH
export PATH=$PATH:/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/
export RUBYOPT=rubygems

export JAVA_HOME=/Library/Java/Home
export CATALINA_HOME=/Library/Tomcat/Home
export ANT_HOME=/usr/share/ant
export ANT_OPTS="-Xms1024m -Xmx1024m" 

export CLASSPATH=junit_lib/junit-4.8.1.jar:.

alias firefox-dev='/Applications/Firefox.app/Contents/MacOS/firefox-bin -p "dev" -no-remote'
export PATH=/usr/texbin:$PATH


[[ -s "$HOME/.rvm/scripts/rvm" ]] && . "$HOME/.rvm/scripts/rvm"  # This loads RVM into a shell session.


#export DYLD_LIBRARY_PATH="$MAGICK_HOME/lib"


function go() {
    rvm use $2
    cd $1
    export GEM_HOME=$1/gems/1.8.7
    export GEM_PATH=$1/gems/1.8.7/bin
    export PATH=$1/gems/1.8.7/bin:$PATH
}

alias gpes='go /Users/ms333/projects/ats/code/galileo/gpe-server ree'
alias gpess='go /Users/ms333/projects/ats/code/gpe-server.git ree'
alias gpeu='go /Users/ms333/projects/ats/code/galileo/ui ree'
alias gpea='go /Users/ms333/projects/ats/code/galileo/api ree'
alias gpea2='go /Users/ms333/projects/ats/code/galileo/api2 ree'
alias gpet='go /Users/ms333/projects/ats/code/galileo/testing ree'

export PATH=/Users/ms333/.cabal/bin:$PATH
#export USERWM=`which xmonad`

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

function fiec() { find $1 -type f -iname '*'${2:-}'*' -exec ${3:-file} {} \;; }
